version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./database:/data  # Montre le dossier contenant init.sql
    environment:
      - PORT=5000

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - CHOKIDAR_USEPOLLING=true

  sqlite-container:
    image: alpine:latest
    command: sh -c "apk --no-cache add sqlite && sqlite3 /data/db.sqlite < /data/init.sql && tail -f /dev/null"
    container_name: sqlite-container
    volumes:
      - ./database:/data